version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '88:cf:0d:96:39:cc:84:fe:8a:82:7b:e1:25:67:1b:47'
      - node/with-cache:
          steps:
            - run: npm install
            - run: git config --global user.email circleci@circleci
            - run: git config --global user.name CircleCI
            - run: npm run deploy-gh
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
        filters:
          branches:
            only:
              - master
