version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    filters:
      branches:
        only:
          - master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm deploy-gh
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
